name: Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

# Prevent concurrent runs for the same branch to avoid race conditions when tagging
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    # Add contents: write permission for pushing tags
    permissions:
      contents: write # Needed to push tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Fetch all tags to check for existing tags
        with:
          fetch-depth: 0 # Fetches all history and tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run tests with coverage
        run: |
          export CGO_ENABLED=0
          go test -coverprofile=cover.out .
          go tool cover -func=cover.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cover.out
